### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by sl2bigdata** [solytic/sql-spark-connector#10]
Hi,

After the mvn build I'm still getting this error when using it on Databricks 11.3 lts runtime.
Any idea?

I'm using pom file of the repo.

 df\
    .repartition(df.count() // batchSize + 1)\
    .write\
    .format("com.microsoft.sqlserver.jdbc.spark")\
    .mode(mode)\
    .option("truncate", True)\
    .option("url", url)\
    .option("dbtable", dbTable)\
    .option("user", user)\
    .option("password", password)\
    .option("driver","com.microsoft.sqlserver.jdbc.SQLServerDriver")\
    .option("batchsize", batchSize)\
    .option("schemaCheckEnabled",False)\
    .save()

Py4JJavaError: An error occurred while calling o3400.save.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getSchema(Ljava/sql/ResultSet;Lorg/apache/spark/sql/jdbc/JdbcDialect;Z)Lorg/apache/spark/sql/types/StructType;
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.matchSchemas(BulkCopyUtils.scala:305)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.getColMetaData(BulkCopyUtils.scala:266)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:66)
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:66)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:78)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:89)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:241)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:243)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:391)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:188)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:973)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:341)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:241)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:226)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:239)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:232)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:99)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:268)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:232)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:232)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:186)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:177)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:268)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:964)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:430)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:397)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Stivo** [comment]
I am getting the same. It seems like in the normal spark 3.3.0 jar this is the method signature:
https://github.com/apache/spark/blob/v3.3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala
 def getSchema(
      resultSet: ResultSet,
      dialect: JdbcDialect,
      alwaysNullable: Boolean = false): StructType = {

However on a databricks notebook I am seeing this signature:
getSchema: (resultSet: java.sql.ResultSet, dialect: org.apache.spark.sql.jdbc.JdbcDialect, alwaysNullable: Boolean, isTimestampNTZ: Boolean)org.apache.spark.sql.types.StructType

There is an additional parameter with a default value on this method in the databricks jar, so they are not binary compatible.

Probably this library would have to be recompiled against the databricks jar for this to work.

**Comment by moredatapls** [comment]
@sl2bigdata @Stivo sorry for the late reply. Did you resolve this issue in the meantime? I can indeed reproduce the bug on my side but I have no idea why it happens.

A side note, @sl2bigdata: partitioning by the count is a bad idea. The whole point of this connector is that it supports batch loading, but in your case you will have very small partitions (a single row). Also, Spark is not good at handling extremely tiny and many partitions, which would happen if your data frame as a large number of rows

> .repartition(df.count() // batchSize + 1)

**Comment by moredatapls** [comment]
Seems like other Spark libraries had similar problems before: https://github.com/crealytics/spark-excel/issues/585#issuecomment-1115809425

> The Databricks support answers the same thing : "We checked with the engineering team, this issue is happening because of the class constructor change from the engineering team".

It could be that Databricks added some changes to their builds

**Comment by tfabritz** [comment]
I see similar issues when using truncate. Could this be caused by the removal of the StructType import in src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/BulkCopyUtils.scala?

**Comment by moredatapls** [comment]
I don't think so @tfabritz, are you referring to this change? https://github.com/solytic/sql-spark-connector/pull/8/files#diff-32770180d1ecf96ad86bdfd65565104ebe7c01f52c81647fd506f43a4739f874

The import was unused. And since the project compiles against plain Spark 3.3.0 I would guess that Databricks is to blame. Their runtimes are not using vanilla Spark, as far as I know.

@tfabritz @sl2bigdata @Stivo: Perhaps you could all open a support request with Databricks so that they can investigate the issue?

**Comment by tfabritz** [comment]
It seems that it got fixed either on Microsoft or Databricks side. The just-released beta worked fine with truncating in a small test I just did.

**Comment by moredatapls** [comment]
You mean the official Microsoft connector here? https://github.com/microsoft/sql-spark-connector/releases/tag/v1.3.0 That's good

**Comment by tfabritz** [comment]
Yes, thats the release I meant. I should have added a link, sorry for that :)
